export enum ContactStatus {
  UNSET = "UNSET",

  PHASE_1_INITIAL_OUTREACH_MESSAGE_SENT = "PHASE_1_INITIAL_OUTREACH_MESSAGE_SENT",
  PHASE_1_INITIAL_OUTREACH_FOLLOW_UP_1 = "PHASE_1_INITIAL_OUTREACH_FOLLOW_UP_1",
  PHASE_1_INITIAL_OUTREACH_FOLLOW_UP_2 = "PHASE_1_INITIAL_OUTREACH_FOLLOW_UP_2",

  PHASE_2_DATA_INQUIRY_BEGIN = "PHASE_2_DATA_INQUIRY_BEGIN",
  PHASE_2_DATA_INQUIRY_END = "PHASE_2_DATA_INQUIRY_END",

  PHASE_3_ONBOARDING_BEGIN = "PHASE_3_ONBOARDING_BEGIN",
  PHASE_3_ONBOARDING_END = "PHASE_3_ONBOARDING_END",

  PHASE_4_MEETING_SCHEDULE_MESSAGE_SENT = "PHASE_4_MEETING_SCHEDULE_MESSAGE_SENT",
  PHASE_4_MEETING_SCHEDULE_FOLLOW_UP_1 = "PHASE_4_MEETING_SCHEDULE_FOLLOW_UP_1",
  PHASE_4_MEETING_SCHEDULE_FOLLOW_UP_2 = "PHASE_4_MEETING_SCHEDULE_FOLLOW_UP_2",

  FINAL_THANK_YOU = "FINAL_THANK_YOU",
}
